"""added discount to expenses

Revision ID: 82ab3fdd0a01
Revises: b20680ab5009
Create Date: 2025-08-22 10:08:38.760061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ab3fdd0a01'
down_revision = 'b20680ab5009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=False, server_default='0.0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy_expenses', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
