"""Initial migration

Revision ID: 880758f9ae03
Revises: 
Create Date: 2025-08-16 16:52:09.401403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880758f9ae03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sold_units', sa.Integer(), nullable=False),
    sa.Column('buying_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('lab', 'imaging', name='test_category_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('receptionist', 'nurse', 'doctor', 'lab_tech', 'imaging_tech', 'pharmacist', 'admin', name='user_roles'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('chief_complain', sa.Text(), nullable=True),
    sa.Column('physical_exam', sa.Text(), nullable=True),
    sa.Column('systemic_exam', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_consultations_doctor_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consultations_patient_id_patients')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('blood_pressure', sa.String(length=15), nullable=False),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('respiration_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], name=op.f('fk_triage_records_nurse_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_triage_records_patient_id_patients')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('pharmacist_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'dispensed', name='prescription_status_enum'), nullable=False),
    sa.Column('dispensed_units', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations')),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_prescriptions_medicine_id_medicines')),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], name=op.f('fk_prescriptions_pharmacist_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='test_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_test_requests_consultation_id_consultations')),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('fk_test_requests_technician_id_users')),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], name=op.f('fk_test_requests_test_type_id_test_types')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('triage_id', sa.Integer(), nullable=True),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('reception', 'waiting_triage', 'waiting_consultation', 'waiting_lab', 'waiting_imaging', 'waiting_pharmacy', 'complete', name='visit_stage_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_visits_consultation_id_consultations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_visits_patient_id_patients')),
    sa.ForeignKeyConstraint(['triage_id'], ['triage_records.id'], name=op.f('fk_visits_triage_id_triage_records')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'mpesa', name='payment_method_enum'), nullable=False),
    sa.Column('mpesa_receipt', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('test_request_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('receptionist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_payments_prescription_id_prescriptions')),
    sa.ForeignKeyConstraint(['receptionist_id'], ['users.id'], name=op.f('fk_payments_receptionist_id_users')),
    sa.ForeignKeyConstraint(['test_request_id'], ['test_requests.id'], name=op.f('fk_payments_test_request_id_test_requests')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_payments_visit_id_visits')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('visits')
    op.drop_table('test_requests')
    op.drop_table('prescriptions')
    op.drop_table('triage_records')
    op.drop_table('consultations')
    op.drop_table('users')
    op.drop_table('test_types')
    op.drop_table('patients')
    op.drop_table('medicines')
    # ### end Alembic commands ###
