"""Auto migration

Revision ID: 91541c160d02
Revises: 6906fea8c2bd
Create Date: 2025-08-30 08:45:19.113011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91541c160d02'
down_revision = '6906fea8c2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('next_of_kin_name')

    # ### end Alembic commands ###
