"""update tables after model changes

Revision ID: b20680ab5009
Revises: 4ef2840215c3
Create Date: 2025-08-21 14:17:24.381493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20680ab5009'
down_revision = '4ef2840215c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otc_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.Enum('reception', 'waiting_pharmacy', 'complete', name='otc_stage_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity_added', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_pharmacy_expenses_medicine_id_medicines')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otc_sale_id', sa.Integer(), nullable=False),
    sa.Column('pharmacist_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('dispensed_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('fk_pharmacy_sales_medicine_id_medicines')),
    sa.ForeignKeyConstraint(['otc_sale_id'], ['otc_sales.id'], name=op.f('fk_pharmacy_sales_otc_sale_id_otc_sales')),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], name=op.f('fk_pharmacy_sales_pharmacist_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=False, server_default="200"))


    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otc_sale_id', sa.Integer(), nullable=True))
        batch_op.alter_column('visit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_payments_test_request_id_test_requests', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_prescription_id_prescriptions', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_otc_sale_id_otc_sales'), 'otc_sales', ['otc_sale_id'], ['id'])
        batch_op.drop_column('test_request_id')
        batch_op.drop_column('prescription_id')

    with op.batch_alter_table('test_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_test_requests_visit_id_visits'), 'visits', ['visit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_test_requests_visit_id_visits'), type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_request_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_payments_otc_sale_id_otc_sales'), type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_prescription_id_prescriptions', 'prescriptions', ['prescription_id'], ['id'])
        batch_op.create_foreign_key('fk_payments_test_request_id_test_requests', 'test_requests', ['test_request_id'], ['id'])
        batch_op.alter_column('visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('otc_sale_id')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_column('fee')

    op.drop_table('pharmacy_sales')
    op.drop_table('pharmacy_expenses')
    op.drop_table('otc_sales')
    # ### end Alembic commands ###
